### ISSUE TITLE
What's `REACT_APP_ENDPOINT`?

### ISSUE THREAD

**Issue by yorzi** [ganezasan/react-cognito-auth#1]
I set .evn file as below:

```
REACT_APP_USER_POOL_ID=us-west-2_Nb1nwOSS
REACT_APP_CLIENT_ID=5dqpg809aku9l1tbv1itu20v
REACT_APP_ENDPOINT=https://29u6lvtd.execute-api.us-west-2.amazonaws.com/dev/
```

But I got below error when I run `npm start`
<img width="552" alt="screen shot 2017-06-09 at 10 06 50 am" src="https://user-images.githubusercontent.com/38976/26958158-99bb16ae-4cfb-11e7-8380-d7f6fce23472.png">

I guess I set the incorrect `REACT_APP_ENDPOINT` value, what should it be? 

Thanks.

**Comment by ganezasan** [comment]
Sorry, REACT_APP_ENDPOINT is just API endpoint.
I was supposed to use this repo.
> https://github.com/ganezasan/serverless-custom-auth-example

The cause of this error is due to package version of React.
I fixed it, so please try `git pull`. Thanks
> https://github.com/ganezasan/react-cognito-auth/commit/c45d228f20fee511d341ac2262a09a021e318c77
